import Head from "next/head";

import { motion as m } from "framer-motion";

const SignUp = () => {
  return (
    <m.div
      className="signup"
      animate={{ opacity: [0, 1] }}
      exit={{ opacity: 0 }}
      transition={{ duration: 0.3 }}
    >
      <Head>
        <title>Sing Up</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      sign-up
    </m.div>
  );
};

export default SignUp;
